title: Mingchao's Blog

author: Mingchao Liao
email: mingchaoliao95@gmail.com

description: >-
  A place to log some random thoughts and share interesting things
  with whoever wants to listen. Who am I? The husband of my wife, a
  full-stack software developer, a slave to my cat, and more.
baseurl: ""
url: ""

github_username:  mingchaoliao
linkedin_username: mingchao-liao-7874188b

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
