version: '3.2'

services:
  blog:
    image: jekyll/jekyll:3.8.5
    command: ["jekyll", "serve", "--watch"]
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000